services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - brvjeoCloud
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  broker:
    image: "rabbitmq:alpine"
    restart: always
    networks:
      - brvjeoCloud
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 10s
      retries: 5

  result:
    image: "redis:alpine"
    restart: always
    networks:
      - brvjeoCloud

  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    command: >
      sh -c "
            python manage.py makemigrations &&
            python manage.py migrate --no-input && 
            python manage.py runserver 0.0.0.0:8082"
    # gunicorn --bind 0.0.0.0:8082 brvjeoCloud.wsgi:application
    # python manage.py runserver_plus 0.0.0.0:8082 --cert-file certs/cert.pem --key-file certs/key.pem

    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
      result:
        condition: service_started
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DEFENDER_REDIS_URL: ${DEFENDER_REDIS_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      REDIS_URL: ${REDIS_URL}
      PORT: 8082
    networks:
      - brvjeoCloud
    volumes:
      - .:/app/backend
      - /app/.venv
    

  celery:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    command: celery --app=brvjeoCloud.celery_app worker --loglevel=info
    depends_on:
      db:
        condition: service_started
      broker:
        condition: service_healthy
      result:
        condition: service_started
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      REDIS_URL: ${REDIS_URL}
    networks:
      - brvjeoCloud
    volumes:
      - .:/app/backend
      - /app/.venv
    
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - brvjeoCloud

  # celery_beat:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   restart: always
  #   command: celery --app=brvjeoCloud.celery_app beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=info
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     broker:
  #       condition: service_healthy
  #     result:
  #       condition: service_started
  #     app:
  #       condition: service_started
  #   environment:
  #     DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
  #     SECRET_KEY: ${SECRET_KEY}
  #     ALLOWED_HOSTS: ${ALLOWED_HOSTS}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     CELERY_BROKER_URL: ${CELERY_BROKER_URL}
  #     REDIS_URL: ${REDIS_URL}
  #   networks:
  #     - brvjeoCloud

volumes:
  dbdata:
    name: brvjeoCloud_dbdata

networks:
  brvjeoCloud:
    driver: bridge
